const KEY='simad_data_v1';
const state=JSON.parse(localStorage.getItem(KEY)||'{"suratMasuk":[],"suratKeluar":[],"arsip":[],"agenda":[]}');
const configs={
 'surat-masuk':{key:'suratMasuk',title:'Surat Masuk',subtitle:'Pencatatan dan pengelolaan surat yang diterima',fields:[['nomor','Nomor Surat','text'],['tanggal','Tanggal','date'],['asal','Asal/Instansi','text'],['perihal','Perihal','text'],['disposisi','Disposisi','text']],cols:[['nomor','Nomor Surat'],['tanggal','Tanggal'],['asal','Asal'],['perihal','Perihal'],['disposisi','Disposisi']]},
 'surat-keluar':{key:'suratKeluar',title:'Surat Keluar',subtitle:'Pencatatan surat dinas yang diterbitkan',fields:[['nomor','Nomor Surat','text'],['tanggal','Tanggal','date'],['tujuan','Tujuan/Instansi','text'],['perihal','Perihal','text'],['keterangan','Keterangan','text']],cols:[['nomor','Nomor Surat'],['tanggal','Tanggal'],['tujuan','Tujuan'],['perihal','Perihal'],['keterangan','Keterangan']]},
 'arsip':{key:'arsip',title:'Arsip Dokumen',subtitle:'Daftar arsip dan dokumen administrasi',fields:[['kode','Kode Arsip','text'],['nama','Nama Dokumen','text'],['kategori','Kategori','text'],['tanggal','Tanggal','date'],['lokasi','Lokasi Penyimpanan','text']],cols:[['kode','Kode'],['nama','Nama Dokumen'],['kategori','Kategori'],['tanggal','Tanggal'],['lokasi','Lokasi']]},
 'agenda':{key:'agenda',title:'Agenda Kegiatan',subtitle:'Jadwal rapat dan kegiatan kedinasan',fields:[['tanggal','Tanggal','date'],['waktu','Waktu','time'],['kegiatan','Kegiatan','text'],['tempat','Tempat','text'],['penanggungJawab','Penanggung Jawab','text']],cols:[['tanggal','Tanggal'],['waktu','Waktu'],['kegiatan','Kegiatan'],['tempat','Tempat'],['penanggungJawab','Penanggung Jawab']]}
};
const app=document.getElementById('app');
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function page(p){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===p));if(p==='dashboard')renderDashboard();else renderTable(p);}
function renderDashboard(){document.getElementById('page-title').textContent='Dashboard';document.getElementById('page-subtitle').textContent='Ringkasan administrasi perkantoran';const total=Object.values(state).reduce((a,x)=>a+x.length,0);app.innerHTML=`<div class="stats"><div class="stat"><small>Total Surat Masuk</small><strong>${state.suratMasuk.length}</strong></div><div class="stat"><small>Total Surat Keluar</small><strong>${state.suratKeluar.length}</strong></div><div class="stat"><small>Total Arsip</small><strong>${state.arsip.length}</strong></div><div class="stat"><small>Total Agenda</small><strong>${state.agenda.length}</strong></div></div><div class="panel"><div class="panel-head"><h2>Aktivitas Administrasi</h2></div><div class="chart"><div class="bar" style="height:${Math.max(10,state.suratMasuk.length*12)}%"><span>Surat Masuk</span></div><div class="bar" style="height:${Math.max(10,state.suratKeluar.length*12)}%"><span>Surat Keluar</span></div><div class="bar" style="height:${Math.max(10,state.arsip.length*12)}%"><span>Arsip</span></div><div class="bar" style="height:${Math.max(10,state.agenda.length*12)}%"><span>Agenda</span></div></div></div><div class="panel"><div class="panel-head"><h2>Akses Cepat</h2></div><div class="quick"><button onclick="openModal('surat-masuk')"><b>📥 Tambah Surat Masuk</b><span>Catat surat yang baru diterima</span></button><button onclick="openModal('surat-keluar')"><b>📤 Tambah Surat Keluar</b><span>Catat surat dinas yang diterbitkan</span></button><button onclick="openModal('arsip')"><b>🗂️ Tambah Arsip</b><span>Daftarkan dokumen ke arsip</span></button></div></div><div class="notice">💡 Total ${total} data tersimpan secara lokal di browser ini. Gunakan tombol ekspor pada setiap modul untuk membuat file CSV.</div>`}
function renderTable(p){const c=configs[p];document.getElementById('page-title').textContent=c.title;document.getElementById('page-subtitle').textContent=c.subtitle;app.innerHTML=`<div class="panel"><div class="toolbar"><input class="search" id="search" placeholder="Cari data..." oninput="drawRows('${p}')"><button class="btn btn-primary" onclick="openModal('${p}')">+ Tambah Data</button><button class="btn btn-secondary" onclick="exportCSV('${p}')">⇩ Ekspor CSV</button></div><div class="table-wrap"><table><thead><tr>${c.cols.map(x=>`<th>${x[1]}</th>`).join('')}<th>Aksi</th></tr></thead><tbody id="rows"></tbody></table></div></div>`;drawRows(p)}
function drawRows(p){const c=configs[p], q=(document.getElementById('search')?.value||'').toLowerCase();const rows=state[c.key].filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(q)));document.getElementById('rows').innerHTML=rows.length?rows.map(r=>`<tr>${c.cols.map(x=>`<td>${esc(r[x[0]])}</td>`).join('')}<td class="actions"><button class="btn btn-danger" onclick="removeItem('${p}','${r.id}')">Hapus</button></td></tr>`).join(''):`<tr><td colspan="${c.cols.length+1}" class="empty">Belum ada data.</td></tr>`}
function openModal(p){const c=configs[p];document.getElementById('modal-title').textContent='Tambah '+c.title;document.getElementById('data-form').innerHTML=`<div class="form-grid">${c.fields.map(f=>`<div class="field"><label>${f[1]}</label><input name="${f[0]}" type="${f[2]}" required></div>`).join('')}</div><div class="form-actions"><button type="button" class="btn btn-secondary" onclick="closeModal()">Batal</button><button class="btn btn-primary">Simpan</button></div>`;document.getElementById('data-form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.id=Date.now().toString();state[c.key].push(data);save();closeModal();renderTable(p)};document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function removeItem(p,id){if(confirm('Hapus data ini?')){const k=configs[p].key;state[k]=state[k].filter(x=>x.id!==id);save();drawRows(p)}}
function exportCSV(p){const c=configs[p], data=state[c.key];if(!data.length){alert('Belum ada data untuk diekspor.');return}const head=c.cols.map(x=>x[1]);const lines=[head.join(','),...data.map(r=>c.cols.map(x=>'"'+String(r[x[0]]??'').replace(/"/g,'""')+'"').join(','))];const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8;'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=c.key+'-'+new Date().toISOString().slice(0,10)+'.csv';a.click();URL.revokeObjectURL(a.href)}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>page(b.dataset.page));document.getElementById('modal-close').onclick=closeModal;document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};setInterval(()=>document.getElementById('clock').textContent=new Date().toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'medium'}),1000);page('dashboard');
