const KEY='simad_data_v2';
const old=JSON.parse(localStorage.getItem('simad_data_v1')||'{}');
const state=JSON.parse(localStorage.getItem(KEY)||'{}');
state.suratMasuk=state.suratMasuk||old.suratMasuk||[];state.suratKeluar=state.suratKeluar||old.suratKeluar||[];state.arsip=state.arsip||old.arsip||[];state.agenda=state.agenda||old.agenda||[];state.aset=state.aset||old.aset||[];state.barang=state.barang||[];state.mutasiBarang=state.mutasiBarang||[];
const configs={
 'surat-masuk':{key:'suratMasuk',title:'Surat Masuk',subtitle:'Pencatatan dan pengelolaan surat yang diterima',fields:[['nomor','Nomor Surat','text'],['tanggal','Tanggal','date'],['asal','Asal/Instansi','text'],['perihal','Perihal','text'],['disposisi','Disposisi','text']],cols:[['nomor','Nomor Surat'],['tanggal','Tanggal'],['asal','Asal'],['perihal','Perihal'],['disposisi','Disposisi']]},
 'surat-keluar':{key:'suratKeluar',title:'Surat Keluar',subtitle:'Pencatatan surat dinas yang diterbitkan',fields:[['nomor','Nomor Surat','text'],['tanggal','Tanggal','date'],['tujuan','Tujuan/Instansi','text'],['perihal','Perihal','text'],['keterangan','Keterangan','text']],cols:[['nomor','Nomor Surat'],['tanggal','Tanggal'],['tujuan','Tujuan'],['perihal','Perihal'],['keterangan','Keterangan']]},
 'arsip':{key:'arsip',title:'Arsip Dokumen',subtitle:'Daftar arsip dan dokumen administrasi',fields:[['kode','Kode Arsip','text'],['nama','Nama Dokumen','text'],['kategori','Kategori','text'],['tanggal','Tanggal','date'],['lokasi','Lokasi Penyimpanan','text']],cols:[['kode','Kode'],['nama','Nama Dokumen'],['kategori','Kategori'],['tanggal','Tanggal'],['lokasi','Lokasi']]},
 'agenda':{key:'agenda',title:'Agenda Kegiatan',subtitle:'Jadwal rapat dan kegiatan kedinasan',fields:[['tanggal','Tanggal','date'],['waktu','Waktu','time'],['kegiatan','Kegiatan','text'],['tempat','Tempat','text'],['penanggungJawab','Penanggung Jawab','text']],cols:[['tanggal','Tanggal'],['waktu','Waktu'],['kegiatan','Kegiatan'],['tempat','Tempat'],['penanggungJawab','Penanggung Jawab']]},
 'aset':{key:'aset',title:'Inventarisasi Aset',subtitle:'Pencatatan dan pengelolaan inventaris barang/aset kantor',fields:[['kodeBarang','Kode Barang','text'],['namaBarang','Nama Barang','text'],['kategori','Kategori Aset','text'],['merkType','Merk/Type','text'],['tahunPerolehan','Tahun Perolehan','number'],['jumlah','Jumlah','number'],['satuan','Satuan','text'],['hargaPerolehan','Harga Perolehan','number'],['kondisi','Kondisi','text'],['lokasi','Lokasi','text'],['penanggungJawab','Penanggung Jawab','text'],['keterangan','Keterangan','text']],cols:[['kodeBarang','Kode Barang'],['namaBarang','Nama Barang'],['kategori','Kategori'],['merkType','Merk/Type'],['tahunPerolehan','Tahun'],['jumlah','Jumlah'],['satuan','Satuan'],['hargaPerolehan','Harga Perolehan'],['kondisi','Kondisi'],['lokasi','Lokasi'],['penanggungJawab','Penanggung Jawab'],['keterangan','Keterangan']]}
};
const app=document.getElementById('app');
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function stock(b){return Number(b.stokAwal||0)+state.mutasiBarang.filter(m=>m.barangId===b.id).reduce((n,m)=>n+(m.jenis==='masuk'?Number(m.jumlah):-Number(m.jumlah)),0)}
function page(p){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===p));if(p==='dashboard')renderDashboard();else if(p==='barang-habis-pakai')renderBHP();else renderTable(p)}
function renderDashboard(){document.getElementById('page-title').textContent='Dashboard';document.getElementById('page-subtitle').textContent='Ringkasan administrasi perkantoran';const total=state.suratMasuk.length+state.suratKeluar.length+state.arsip.length+state.agenda.length+state.aset.length+state.barang.length;app.innerHTML=`<div class="stats"><div class="stat"><small>Total Surat Masuk</small><strong>${state.suratMasuk.length}</strong></div><div class="stat"><small>Total Surat Keluar</small><strong>${state.suratKeluar.length}</strong></div><div class="stat"><small>Total Arsip</small><strong>${state.arsip.length}</strong></div><div class="stat"><small>Total Aset</small><strong>${state.aset.length}</strong></div><div class="stat"><small>Jenis Barang Habis Pakai</small><strong>${state.barang.length}</strong></div></div><div class="panel"><div class="panel-head"><h2>Ringkasan Barang Habis Pakai</h2></div><div class="stats"><div class="stat"><small>Total Stok</small><strong>${state.barang.reduce((n,b)=>n+stock(b),0)}</strong></div><div class="stat"><small>Stok Menipis</small><strong>${state.barang.filter(b=>stock(b)<=Number(b.stokMinimum||0)).length}</strong></div><div class="stat"><small>Total Barang Masuk</small><strong>${state.mutasiBarang.filter(m=>m.jenis==='masuk').reduce((n,m)=>n+Number(m.jumlah),0)}</strong></div><div class="stat"><small>Total Barang Keluar</small><strong>${state.mutasiBarang.filter(m=>m.jenis==='keluar').reduce((n,m)=>n+Number(m.jumlah),0)}</strong></div></div></div><div class="panel"><div class="panel-head"><h2>Akses Cepat</h2></div><div class="quick"><button onclick="openModal('barang')"><b>📦 Tambah Barang</b><span>Daftarkan jenis barang habis pakai</span></button><button onclick="openMutasi('masuk')"><b>⬇️ Barang Masuk</b><span>Tambah stok berdasarkan penerimaan</span></button><button onclick="openMutasi('keluar')"><b>⬆️ Barang Keluar</b><span>Catat pengeluaran/pemakaian barang</span></button></div></div><div class="notice">Total ${total} data administrasi tersimpan di browser. Modul Barang Habis Pakai sudah mendukung stok, minimum stok, mutasi masuk/keluar, pencarian dan ekspor CSV.</div>`}
function renderTable(p){const c=configs[p];document.getElementById('page-title').textContent=c.title;document.getElementById('page-subtitle').textContent=c.subtitle;app.innerHTML=`<div class="panel"><div class="toolbar"><input class="search" id="search" placeholder="Cari data..." oninput="drawRows('${p}')"><button class="btn btn-primary" onclick="openModal('${p}')">+ Tambah Data</button><button class="btn btn-secondary" onclick="exportCSV('${p}')">⇩ Ekspor CSV</button></div><div class="table-wrap"><table><thead><tr>${c.cols.map(x=>`<th>${x[1]}</th>`).join('')}<th>Aksi</th></tr></thead><tbody id="rows"></tbody></table></div></div>`;drawRows(p)}
function drawRows(p){const c=configs[p],q=(document.getElementById('search')?.value||'').toLowerCase(),rows=state[c.key].filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(q)));document.getElementById('rows').innerHTML=rows.length?rows.map(r=>`<tr>${c.cols.map(x=>`<td>${esc(r[x[0]])}</td>`).join('')}<td class="actions"><button class="btn btn-danger" onclick="removeItem('${p}','${r.id}')">Hapus</button></td></tr>`).join(''):`<tr><td colspan="${c.cols.length+1}" class="empty">Belum ada data.</td></tr>`}
function openModal(p){const c=configs[p];document.getElementById('modal-title').textContent='Tambah '+c.title;document.getElementById('data-form').innerHTML=`<div class="form-grid">${c.fields.map(f=>`<div class="field"><label>${f[1]}</label><input name="${f[0]}" type="${f[2]}" min="0" required></div>`).join('')}</div><div class="form-actions"><button type="button" class="btn btn-secondary" onclick="closeModal()">Batal</button><button class="btn btn-primary">Simpan</button></div>`;document.getElementById('data-form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.id=Date.now().toString();state[c.key].push(data);save();closeModal();renderTable(p)};document.getElementById('modal').classList.remove('hidden')}
function renderBHP(){document.getElementById('page-title').textContent='Barang Habis Pakai';document.getElementById('page-subtitle').textContent='Pengelolaan persediaan, penerimaan dan pengeluaran barang';const low=state.barang.filter(b=>stock(b)<=Number(b.stokMinimum||0));app.innerHTML=`<div class="stats"><div class="stat"><small>Jenis Barang</small><strong>${state.barang.length}</strong></div><div class="stat"><small>Total Stok</small><strong>${state.barang.reduce((n,b)=>n+stock(b),0)}</strong></div><div class="stat"><small>Stok Menipis</small><strong>${low.length}</strong></div><div class="stat"><small>Mutasi</small><strong>${state.mutasiBarang.length}</strong></div></div><div class="panel"><div class="toolbar"><input class="search" id="bhp-search" placeholder="Cari kode, nama, kategori..." oninput="drawBHP()"><button class="btn btn-primary" onclick="openModal('barang')">+ Tambah Barang</button><button class="btn btn-secondary" onclick="openMutasi('masuk')">⬇️ Barang Masuk</button><button class="btn btn-secondary" onclick="openMutasi('keluar')">⬆️ Barang Keluar</button><button class="btn btn-secondary" onclick="exportBHP()">⇩ Ekspor Stok</button><button class="btn btn-secondary" onclick="exportMutasi()">⇩ Ekspor Mutasi</button></div><div class="table-wrap"><table><thead><tr><th>Kode</th><th>Nama Barang</th><th>Kategori</th><th>Satuan</th><th>Stok</th><th>Min. Stok</th><th>Status</th><th>Lokasi</th><th>Aksi</th></tr></thead><tbody id="bhp-rows"></tbody></table></div></div><div class="panel"><div class="panel-head"><h2>Peringatan Stok Minimum</h2></div>${low.length?low.map(b=>`<div class="notice">⚠️ <b>${esc(b.nama)}</b> tersisa ${stock(b)} ${esc(b.satuan)} (minimum ${b.stokMinimum}).</div>`).join(''):'<div class="notice">✅ Tidak ada barang yang berada di bawah stok minimum.</div>'}</div>`;drawBHP()}
function drawBHP(){const q=(document.getElementById('bhp-search')?.value||'').toLowerCase(),rows=state.barang.filter(b=>Object.values(b).some(v=>String(v).toLowerCase().includes(q)));document.getElementById('bhp-rows').innerHTML=rows.length?rows.map(b=>{const s=stock(b),min=Number(b.stokMinimum||0),status=s<=min?'MENIPIS':'AMAN';return `<tr><td>${esc(b.kode)}</td><td>${esc(b.nama)}</td><td>${esc(b.kategori)}</td><td>${esc(b.satuan)}</td><td><b>${s}</b></td><td>${min}</td><td>${status}</td><td>${esc(b.lokasi)}</td><td class="actions"><button class="btn btn-secondary" onclick="openMutasi('masuk','${b.id}')">Masuk</button> <button class="btn btn-secondary" onclick="openMutasi('keluar','${b.id}')">Keluar</button> <button class="btn btn-danger" onclick="removeBHP('${b.id}')">Hapus</button></td></tr>`}).join(''):`<tr><td colspan="9" class="empty">Belum ada barang.</td></tr>`}
function openBarangForm(){document.getElementById('modal-title').textContent='Tambah Barang Habis Pakai';document.getElementById('data-form').innerHTML=`<div class="form-grid"><div class="field"><label>Kode Barang</label><input name="kode" required></div><div class="field"><label>Nama Barang</label><input name="nama" required></div><div class="field"><label>Kategori</label><input name="kategori" placeholder="ATK, kebersihan, cetak..." required></div><div class="field"><label>Satuan</label><input name="satuan" placeholder="rim, pcs, box, botol..." required></div><div class="field"><label>Stok Awal</label><input name="stokAwal" type="number" min="0" value="0" required></div><div class="field"><label>Minimum Stok</label><input name="stokMinimum" type="number" min="0" value="0" required></div><div class="field"><label>Lokasi Penyimpanan</label><input name="lokasi" required></div><div class="field"><label>Keterangan</label><input name="keterangan"></div></div><div class="form-actions"><button type="button" class="btn btn-secondary" onclick="closeModal()">Batal</button><button class="btn btn-primary">Simpan</button></div>`;document.getElementById('data-form').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.id=Date.now().toString();state.barang.push(d);save();closeModal();renderBHP()};document.getElementById('modal').classList.remove('hidden')}
function openMutasi(jenis,id=''){document.getElementById('modal-title').textContent=jenis==='masuk'?'Penerimaan Barang':'Pengeluaran Barang';const options=state.barang.map(b=>`<option value="${b.id}" ${b.id===id?'selected':''}>${esc(b.kode)} - ${esc(b.nama)} (stok ${stock(b)} ${esc(b.satuan)})</option>`).join('');document.getElementById('data-form').innerHTML=`<div class="form-grid"><div class="field"><label>Barang</label><select name="barangId" required>${options||'<option value="">Belum ada barang</option>'}</select></div><div class="field"><label>Tanggal</label><input name="tanggal" type="date" value="${new Date().toISOString().slice(0,10)}" required></div><div class="field"><label>Jumlah</label><input name="jumlah" type="number" min="1" required></div><div class="field"><label>No. Dokumen/Bukti</label><input name="dokumen" placeholder="Faktur, nota, BAST, bon..." required></div><div class="field"><label>Petugas/Penerima</label><input name="petugas" required></div><div class="field"><label>Keterangan</label><input name="keterangan"></div></div><div class="form-actions"><button type="button" class="btn btn-secondary" onclick="closeModal()">Batal</button><button class="btn btn-primary" ${options?'':'disabled'}>Simpan</button></div>`;document.getElementById('data-form').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.id=Date.now().toString();d.jenis=jenis;const b=state.barang.find(x=>x.id===d.barangId);if(jenis==='keluar'&&Number(d.jumlah)>stock(b)){alert('Stok tidak mencukupi. Stok tersedia: '+stock(b));return}state.mutasiBarang.push(d);save();closeModal();renderBHP()};document.getElementById('modal').classList.remove('hidden')}
function exportBHP(){const head=['Kode','Nama','Kategori','Satuan','Stok','Minimum','Status','Lokasi','Keterangan'];const lines=[head.join(','),...state.barang.map(b=>[b.kode,b.nama,b.kategori,b.satuan,stock(b),b.stokMinimum,stock(b)<=Number(b.stokMinimum||0)?'MENIPIS':'AMAN',b.lokasi,b.keterangan].map(csv).join(','))];download(lines,'stok-barang-habis-pakai.csv')}
function exportMutasi(){const head=['Tanggal','Jenis','Kode','Nama','Jumlah','Satuan','Dokumen','Petugas','Keterangan'];const lines=[head.join(','),...state.mutasiBarang.map(m=>{const b=state.barang.find(x=>x.id===m.barangId)||{};return [m.tanggal,m.jenis,b.kode,b.nama,m.jumlah,b.satuan,m.dokumen,m.petugas,m.keterangan].map(csv).join(',')})];download(lines,'mutasi-barang-habis-pakai.csv')}
function csv(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}function download(lines,name){const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8;'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportCSV(p){const c=configs[p],data=state[c.key];if(!data.length){alert('Belum ada data untuk diekspor.');return}download([c.cols.map(x=>x[1]).join(','),...data.map(r=>c.cols.map(x=>csv(r[x[0]])).join(','))],c.key+'-'+new Date().toISOString().slice(0,10)+'.csv')}
function removeItem(p,id){if(confirm('Hapus data ini?')){const k=configs[p].key;state[k]=state[k].filter(x=>x.id!==id);save();drawRows(p)}}function removeBHP(id){if(confirm('Hapus barang ini beserta riwayat mutasinya?')){state.barang=state.barang.filter(x=>x.id!==id);state.mutasiBarang=state.mutasiBarang.filter(x=>x.barangId!==id);save();renderBHP()}}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
const oldOpenModal=openModal;openModal=function(p){if(p==='barang')openBarangForm();else oldOpenModal(p)};
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>page(b.dataset.page));document.getElementById('modal-close').onclick=closeModal;document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};setInterval(()=>document.getElementById('clock').textContent=new Date().toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'medium'}),1000);page('dashboard');
